apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lab02first
  name: lab02first
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab02first
  strategy: {}
  template:
    metadata:
      labels:
        app: lab02first
        owner: {your name here} # <<<<<<<<< UPDATE
    spec:
      containers:
      - image: httpd
        name: httpd
status: {}
