apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-images

spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: disallow-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Deployment

      validate:
        message: "Images must not use the 'latest' tag."

        foreach:
          - list: "request.object.spec.template.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.image }}"
                    operator: EndsWith
                    value: ":latest"