apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab3web
  name: lab3web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab3web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab3web
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
