apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kvstore
  name: kvstore
spec:
  containers:
  - image: abhirockzz/kvstore
    name: kvstore
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-vol
    emptyDir: {}
